name: Build deb packages

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [{os: debian, dist: [buster, bullseye, bookworm], suffix: -slim}, {os: ubuntu, dist: [trusty, xenial, bionic, focal, jammy, jammy, kinetic]}]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Changing debian changelog
      run: |
        sudo apt-get update
        sudo apt-get install devscripts
        debchange -v "`git describe --tags`-${{ matrix.image.dist }}" -b -M --distribution ${{ matrix.image.dist }} "trunk build"
    - name: Building package
      uses: jtdor/build-deb-action@v1
      with:
        docker-image: ${{ matrix.image.os }}:${{ matrix.image.dist }}${{ matrix.image.suffix }}
        buildpackage-opts: --build=binary --no-sign
    - name: Uploading package to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: i2pd_${{ matrix.image.dist }}
        path: debian/artifacts/i2pd_*.deb
    - name: Uploading debug symbols to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: i2pd-dbgsym_${{ matrix.image.dist }}
        path: debian/artifacts/i2pd-dbgsym_*.deb
